### ISSUE TITLE
discussion - app binder into a processes binder auto killer windows service

### ISSUE THREAD

**Issue by jwallet** [TenteEEEE/app_binder#6]
Hi there,

Thanks for adding this project to github, I was looking for a starting point to make it possible to bind a torrent client with my vpn GUI and this is the closest thing I found. I may fork your project to make some changes and push a PR if you wish.

So my use case is: many vpn apps has a auto killer setting that kills any user listed apps when the vpn gets disconnected, but when the GUI dies it does nothing, and the torrent app keeps running without the VPN. Also some of these VPN don't allow to use their service without the GUI, so impossible to run it as a torrent proxy.

I think everyone using NordVPN, for instance, or the torrent community in general would be so pleased to use this process binder.

So to make this possible, these are the changes I think I would implement in the fork, let me know what you think:

- Make it start when Windows start, turn the app into a windows process service.
- Make it possible to set a master or slave app to an app as an option to a process.
- When one of the master apps dies, all of his slaves apps must be terminated.

**Comment by TenteEEEE** [comment]
Thank you for your suggestion.
I very welcome your suggestions for improving the usability of AppBinder.

These suggestions seem to be good enhancements to the app, so I do not have any reasons to reject the suggestions.
However, I am just wondering why this app needs to run as a Windows service.
Is it for user permissions or to control another Windows service (the VPN client is working as a service)?

Anyway, I am rooting for you.
If you have any questions about this app, please let me know.

**Comment by jwallet** [comment]
in this case the app would be used on a server or a virtual machine.
what having it as a service would do:
- it always starts when the server restart. services normally never fail to start 
- it starts even if the user is not logged in, an app would only run if a user is connected (locked session also work)
- when logged in, it starts before apps in the startup folder. 
- also, it is possible to define rules from windows service
   - logon rule
   - recovery
   - dependencies
   - start parameters, if we make it possible to start the app with command arguments like without the GUI, only as a command line like so `app-binder.exe -master=".../excel.exe" -slave="../notepad.exe"`

i will close this one, since it is not an issue

**Comment by TenteEEEE** [comment]
I understand.
These features are suitable for the app.
I will cooperate for you as much as I can.
When you want to ask something, please reopen the issue or open a new issue.
